### ISSUE TITLE
Doesn't process large files

### ISSUE THREAD

**Issue by tjhorner** [sysdream/Protod#1]
I'm trying to process a relatively large binary (35MB!) with Protod, but I'm getting `OverflowError`s. If I get it working, I'll close this issue and send over a PR.

Stacktrace:

``` python
Traceback (most recent call last):
  File "protod.py", line 315, in <module>
    extractor.extract()
  File "protod.py", line 274, in extract
    for k in range(probable_size+1024, 0, -1):
OverflowError: range() result has too many items
```

**Comment by Manouchehri** [comment]
https://github.com/Manouchehri/Protod/tree/overflow-fix

Untested.
